### ISSUE TITLE
Add CAN PHY and connectors

### ISSUE THREAD

**Issue by jadonk** [jadonk/beaglebone-blue#13]

**Comment by erikwelsh** [comment]
Rev A1 has CAN PHY (TCAN1051HV) and a JST connector for DCAN1.

**Comment by jadonk** [comment]
May need to revisit pin connections. Does that need discussion here before closing this item?

**Comment by StrawsonDesign** [comment]
I like the JST connector, think this can be closed.

Dept. Mechanical & Aerospace Engineering
University of California, San Diego
