### ISSUE TITLE
Add connector for additional GPIOs

### ISSUE THREAD

**Issue by jadonk** [jadonk/beaglebone-blue#15]

**Comment by erikwelsh** [comment]
Rev A1 has two GPIO connectors:
- GPIO0:  4 GPIO pins (JST connector)
- GPIO1: 2 GPIO pins (Grove connector)

GPIO0 uses the following pins (may change in Rev A2):
- Bit 0:  Pin U16 - GPIO1_25
- Bit 1:  Pin V14 - GPIO1_17
- Bit 2:  Pin D13 - GPIO3_20
- Bit 3:  Pin C18 - GPIO0_7

GPIO1 uses the following pins (may change in Rev A2):
- Bit 0:  Pin J15 - GPIO3_2
- Bit 1:  Pin H17 - GPIO3_1
