### ISSUE TITLE
Make new connectors as JST instead of Grove

### ISSUE THREAD

**Issue by jadonk** [jadonk/beaglebone-blue#16]

**Comment by jadonk** [comment]
Done as part of 57fd393b58db450caf035d6a3a34a7a32e0dd2d6

**Comment by erikwelsh** [comment]
Rev A1 has Grove connectors for:
- UART5 (broken due to IOSet issue)
- I2C1
- GPIO (2 pins)

**Comment by jadonk** [comment]
Move to JST connectors to save board space and collapse component list.

**Comment by erikwelsh** [comment]
Changed UART5 and I2C1 to 4 pin JST connectors.
Changed GPIO1 to a 6 pin JST connector (includes 2 GPIO pins as well as the Red and Green LED signals)

**Comment by Scalpel78** [comment]
What is the type of JST connector used called?

**Comment by StrawsonDesign** [comment]
All the little I2C, UART, GPIO, SPI, Encoder, and CAN connectors are JST SH, 4 or 6 pin.
