### ISSUE TITLE
Change 6V_REG soft-start cap to 0.1uf

### ISSUE THREAD

**Issue by StrawsonDesign** [jadonk/beaglebone-blue#35]
6V_REG works on cape but only starts when no load is present on Blue. Cause is likely the 1nF capacitor C21 on Blue. Should change to 0.1uF to match cape.

**Comment by erikwelsh** [comment]
Updated schematics and BOM to change the value of C21.

**Comment by jadonk** [comment]
Can we modify a board to confirm?

**Comment by StrawsonDesign** [comment]
I'll have a go tomorrow.

**Comment by StrawsonDesign** [comment]
confirmed, the capacitor change fixes soft-start

**Comment by jadonk** [comment]
@StrawsonDesign Thanks!!
