### ISSUE TITLE
BT_EN is not an LED

### ISSUE THREAD

**Issue by dlech** [jadonk/beaglebone-blue#43]
I was checking out the LEDs and noticed that there is an LED named `wl18xx_bt_en` that is not actually an LED. It is defined in [am335x-boneblue-wl1835.dtsi](https://github.com/beagleboard/linux/blob/4.4/arch/arm/boot/dts/am335x-boneblue-wl1835.dtsi#L17). Was this an LED in previous revisions of the board? I have rev A2.

**Comment by dlech** [comment]
Also reported this at https://github.com/beagleboard/linux/issues/118

**Comment by jadonk** [comment]
It was an LED in previous revisions. It is still configured as an LED to provide simple controls.
