### ISSUE TITLE
Adjust SPI1 pins

### ISSUE THREAD

**Issue by jadonk** [jadonk/beaglebone-blue#5]
- Use UART0_RTSN (E17) for SPI1_CS0, moving from pin C12.
- Use pin A15 for SPI1_CS1, moving from pin C18.

**Comment by jadonk** [comment]
What wasn't noted that I/O set had to have been followed. This will be deferred to Rev B.

**Comment by erikwelsh** [comment]
To fix the SPI chip select IO set issue, we will change the location of SPI1 CS0 and CS1.  The final pin mapping will be:

spi1_sclk		A13 (mcasp0_aclkx – current pin)
spi1_d0		B13 (mcasp0_fsx – current pin)
spi1_d1		D12 (mcasp0_axr0 – current pin)
spi1_cs0		H18 (rmii1_refclk – currently unused on BB Blue)
spi1_cs1		C18 (eCAP0_in_PWM0_out – currently GPIO_0_3 on BB Blue)
GPIO_0_3		C12 (currently spi1_cs0)
WIFI_LED		A15 (currently spi1_cs1 - See Issue #29 )

**Comment by jadonk** [comment]
There must be an error. How do you have 2 pins be GPIO0_3?

**Comment by erikwelsh** [comment]
Sorry if I was not clear.  The items in quotes was what the function was on Rev A1a.  Basically, we are taking four pads:  H18, C18, C12 and A15 and swapping around the functionality.  The Rev A2 mapping is outside the quotes.  For example, on Rev A1a GPIO_0_3 (ie GPIO connector 0 pin 3, not AM335 GPIO0_3) was C18.  For Rev A2 it will be C12.

**Comment by jadonk** [comment]
@erikwelsh @StrawsonDesign Objections to me changing the net names to reflect the processor GPIO number? I like to avoid people needing to refer to additional documentation in order to program the hardware.
