### ISSUE TITLE
OSD3358 so week?

### ISSUE THREAD

**Issue by h2mille** [jadonk/beaglebone-blue#50]
Hi,
This is my second broken BBBlue, breaking "the same way" I do have 5V line working, but not 3.3V anymore. I just understood the regulator is inside OSD3358 SIP A, and so part of the main chip, that I'm really unable to replace.
For once, I saw my BBB breaking (last time, it didn't boot after no use for a while): a bit intensive usage of two motors (on H1). ANyway, now, the ib led blink  once a  quater second, and disapear. I disconnected the 3.3V pin on h1, still not working. So now... Why the 3.3 power is going through the main processor, instead of going through a succincte regulator?( for the driver, and for output lines too.

At last, is it possible to get a new board Asap? my supplyer will think I'm just bad, and might be lazy to change my boards, as: I broke (but repaired) the usb connector, got this 3.3V problem twice, got the flash  chip burnt one day after getting it (really heating a lot, still can boot a bit on SD), and at last got Q1 burnt (no reason, I changed it this morning)

**Comment by jadonk** [comment]
Q1 will fry if you connect the LiPo battery backwards. Contact me via e-mail, calendar appointment if needed. https://beagleboard.org/about.
