### ISSUE TITLE
WiFi antenna attachment

### ISSUE THREAD

**Issue by dorovl** [jadonk/beaglebone-blue#56]
We had a bad signal intensity (as we where quite far from the router). Therefore, we tried to take out the WiFi antenna to obtain a better a signal intensity. Lot of pictures like https://github.com/beagleboard/beaglebone-blue/blob/master/docs/BeagleBone_Blue_balloons.png illustrate BBBL with the antenna out. Therefore, we don't saw any constraints to rotate the antenna.
 
To rotate the antenna there are two options:

1. Rotate the antenna without extracting it; the risk is to exert an asymmetrical tearing on the whole assembly when passing over the WiFi chip,
2. Extract the antenna from the receptacle, rotate the antenna 180° and push back the antenna on the receptacle.

Option 1 works quite well (tested by me, but not sure that it does not cause exfoliation of the printed circuit board). Option 2 causes the tearing of the receptacle (what happened to my father) because the anchoring of the receptacle on the printed circuit board is only superficial. Therefore, the required extraction force is bigger than the force that the attachment can support. Please note that we applied the instructions of the Hirose Electric connector manufacturer, consisting to to pull off vertically the U.FL Cable Assembly, in the direction of the connector mating axis (we don't used the extraction tool but but some plastic tweezers):

![image006](https://user-images.githubusercontent.com/8594515/70442606-f66d5b80-1a96-11ea-86a0-9c39a75a261a.png)

- **We recommend that on the next version, the anchoring of the receptacle on the printed circuit board must be stronger (attached to a anchorage pin inserted in the PCB); some extraction test should be made on the first prototypes.**
- **For the meantime, a warning notice should be present with the product.**

**Comment by jadonk** [comment]
Issue migrated to beagleboard/beaglebone-blue#41
