### ISSUE TITLE
Grab McASP0 for Bluetooth A2DP I2S interface

### ISSUE THREAD

**Issue by jadonk** [jadonk/beaglebone-blue#6]
* Move MDIR_1A from U18 to P9_12 (C12) to get MCASP0_ACLKR
* Move LED_2 from V12 to P8_32 (T5) to get MCASP0_FSR
* Move USB1_OCn from T16 to GPIO2_21 (M16) to get MCASP0_AXR0
* Remove HDMICLK_DISn from V17 to get MCASP0_AXR1
* Remove HDMI_INT from U16, just in case I need to get MCASP0_FSX

**Comment by jadonk** [comment]
I've confirmed that the McASP connection is not required for connecting to Bluetooth speakers.

**Comment by erikwelsh** [comment]
In Rev A1, BT audio signals are hooked up to McASP0 with the following pins:
- MCASP0_ACLKR - pin U18
- MCASP0_FSR - pin V12
- MCASP0_AXR0 - pin T16
- MCASP0_AXR1 - pin V17

The WL183x did not need MCASP0_FSX.  Therefore, it was not connected.

**Comment by jadonk** [comment]
BeagleBone Green Wireless .dts file has some info on getting this configured. I'm not sure how to get the device in the right mode to verify this functionality.
