### ISSUE TITLE
Address concerns about connector choice

### ISSUE THREAD

**Issue by jadonk** [jadonk/beaglebone-blue#8]
* Could we bundle pig-tails?
  * estimate about $0.10 cost each and likely to bundle about 6 of them
  * 6-wire: https://www.sparkfun.com/products/10361
  * 4-wire: https://www.sparkfun.com/products/9916
  * 2-wire: https://www.sparkfun.com/products/9914
* Where is the documentation for where to buy them?

Why we like them:
* small
* easy to plug and remove
* stay connected well
* readily available

**Comment by jadonk** [comment]
We'll have a solution for pigtails and are happy with these connectors.

**Comment by jiffyjeff** [comment]
> We'll have a solution for pigtails and are happy with these connectors.

With all due respect, I'd appreciate some assistance locating a bundle of these connectors.
